#!/usr/bin/env python3
"""
trading-sim runner — runs the engine on a schedule, commits to git, reports.
Designed to be called by cron every minute.
"""

import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

BASE_DIR = Path("/data/apps/GoalChain/ops/trading-sim")
ENGINE = BASE_DIR / "engine.py"
REPORT_DIR = BASE_DIR / "reports"
LEDGER_PATH = BASE_DIR / "trades.jsonl"
STATE_PATH = BASE_DIR / "state.json"
GIT_DIR = BASE_DIR / ".git"

# Config
COMMIT_EVERY_N_TRADES = 3
REPORT_EVERY_N_TICKS = 60  # ~every 60 minutes


def count_new_trades_since_last_commit():
    """Count trades since last git commit."""
    try:
        result = subprocess.run(
            ["git", "log", "--oneline", "-1", "--format=%H"],
            capture_output=True, text=True, cwd=BASE_DIR
        )
        last_commit = result.stdout.strip()
        if not last_commit:
            return 999
        
        result = subprocess.run(
            ["git", "diff", "--stat", f"{last_commit}..HEAD", "--", "trades.jsonl"],
            capture_output=True, text=True, cwd=BASE_DIR
        )
        if "trades.jsonl" in result.stdout:
            return 999  # file changed
        return 0
    except Exception:
        return 999


def git_commit(message):
    """Commit current state to git."""
    try:
        subprocess.run(["git", "add", "-A"], cwd=BASE_DIR, check=True)
        subprocess.run(
            ["git", "commit", "-m", message],
            cwd=BASE_DIR, capture_output=True
        )
        return True
    except subprocess.CalledProcessError:
        return False


def run_engine_tick():
    """Run one engine tick."""
    result = subprocess.run(
        [sys.executable, str(ENGINE)],
        capture_output=True, text=True, cwd=BASE_DIR, timeout=120
    )
    return result.stdout, result.stderr, result.returncode


def generate_report():
    """Generate a report from the ledger."""
    if not LEDGER_PATH.exists():
        return "No trades yet."
    
    trades = []
    for line in LEDGER_PATH.read_text().splitlines():
        if line.strip():
            try:
                trades.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    
    opens = [t for t in trades if t["event"] == "OPEN"]
    closes = [t for t in trades if t["event"] == "CLOSE"]
    
    total_pnl = sum(t.get("pnl_net", 0) or 0 for t in closes)
    total_fees = sum(t.get("fee_usd", 0) or 0 for t in closes)
    total_slippage = sum(t.get("slippage_usd", 0) or 0 for t in closes)
    
    winners = [t for t in closes if (t.get("pnl_net") or 0) > 0]
    losers = [t for t in closes if (t.get("pnl_net") or 0) < 0]
    
    win_rate = len(winners) / len(closes) * 100 if closes else 0
    avg_win = sum(t["pnl_net"] for t in winners) / len(winners) if winners else 0
    avg_loss = sum(t["pnl_net"] for t in losers) / len(losers) if losers else 0
    
    # Per strategy
    strategies = {}
    for t in closes:
        s = t["strategy"]
        if s not in strategies:
            strategies[s] = {"pnl": 0, "trades": 0, "wins": 0}
        strategies[s]["pnl"] += t.get("pnl_net", 0)
        strategies[s]["trades"] += 1
        if (t.get("pnl_net") or 0) > 0:
            strategies[s]["wins"] += 1
    
    now = datetime.now(timezone.utc)
    
    # Calculate profit factor safely
    total_wins = sum(t['pnl_net'] for t in winners) if winners else 0
    total_losses = sum(t['pnl_net'] for t in losers) if losers else 0
    profit_factor = abs(total_wins / total_losses) if total_losses != 0 else float('inf')
    
    report = f"""# GoalWorld Trading Simulator — Live Report
**{now.strftime('%Y-%m-%d %H:%M:%S')} UTC**

## Portfolio Summary
- **Starting Capital:** $500.00
- **Total P&L:** ${total_pnl:+.4f}
- **Total Fees:** ${total_fees:.4f}
- **Total Slippage:** ${total_slippage:.4f}
- **Return:** {(total_pnl/500)*100:+.2f}%

## Trade Statistics
- **Total Opens:** {len(opens)}
- **Total Closes:** {len(closes)}
- **Open Positions:** {len(opens) - len(closes)}
- **Win Rate:** {win_rate:.1f}%
- **Avg Win:** ${avg_win:+.4f}
- **Avg Loss:** ${avg_loss:+.4f}
- **Profit Factor:** {profit_factor:.2f}

## Per Strategy
"""
    for s, data in strategies.items():
        wr = data["wins"] / data["trades"] * 100 if data["trades"] else 0
        report += f"""### {s}
- P&L: ${data['pnl']:+.4f}
- Trades: {data['trades']} (win rate: {wr:.1f}%)

"""
    
    report += f"\n---\n*Generated by trading-sim runner*"
    
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORT_DIR / f"report_{now.strftime('%Y%m%d_%H%M')}.md"
    report_path.write_text(report)
    
    # Also write latest
    latest_path = REPORT_DIR / "latest.md"
    latest_path.write_text(report)
    
    return report


def main():
    now = datetime.now(timezone.utc)
    print(f"[{now.strftime('%Y-%m-%d %H:%M:%S')} UTC] Trading-sim runner starting")
    
    # Run engine
    stdout, stderr, rc = run_engine_tick()
    
    if rc != 0:
        print(f"[ERROR] Engine returned {rc}: {stderr[:500]}")
        return 1
    
    print(stdout)
    
    # Commit to git if there are new trades
    if LEDGER_PATH.exists():
        new_trades = count_new_trades_since_last_commit()
        if new_trades >= COMMIT_EVERY_N_TRADES or new_trades == 999:
            msg = f"trading-sim: {now.strftime('%Y-%m-%d %H:%M')} UTC — auto commit"
            if git_commit(msg):
                print(f"[GIT] Committed: {msg}")
    
    # Generate report periodically
    tick_count = int(os.environ.get("TICK_COUNT", "0"))
    if tick_count % REPORT_EVERY_N_TICKS == 0:
        report = generate_report()
        print(f"[REPORT] Generated latest report")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())