#!/usr/bin/env python3
"""
Test Alpha Signal with mock data - demonstrates the full output format.
Run this to preview what the daily post will look like.
"""

import json
from datetime import datetime

# Mock data for demonstration
MOCK_DEFI = {
    "protocol": "Jito",
    "vault": "JitoSOL",
    "apy": "8.42%",
    "tvl": "$284M",
    "risk": "LOW",
    "delta_bps": +312,
    "catalyst": "MEV rewards reset + new staking incentives"
}

MOCK_FOOTBALL = {
    "league": "Premier League",
    "team": "Manchester City",
    "player": "Erling Haaland",
    "stat": "xG/90 1.24 vs league avg 0.68; next 3 fixtures: bottom-half defenses",
    "signal_type": "form",
    "details": "Haaland 4 goals in last 2 matches; City face Wolves, Fulham, Brentford"
}

MOCK_HAIKU = """Yield compounds slow
Haaland hunts in the box now
Patience wins the day"""

def format_alpha_signal(defi, football, haiku):
    today = datetime.now().strftime("%d/%m")
    
    # Haiku lines
    haiku_lines = haiku.strip().split('\n')
    
    output = f"""📡 **ALPHA SIGNAL** — {today}

🔗 **THE FUSION**
JitoSOL's APY surged 312bps post-MEV reset while Haaland's xG/90 sits at 1.24 — nearly 2x league average. Both signals scream **asymmetric upside**: DeFi yield compounding quietly, football striker feasting visibly. The market prices both at fair value; the edge is holding through noise.

---

### ⛓️ ON-CHAIN: {defi['protocol']} {defi['vault']}
**Signal**: JitoSOL APY +{defi['delta_bps']}bps post-MEV reset, TVL +8% WoW
**Metric**: APY {defi['apy']} | TVL {defi['tvl']} | Risk: {defi['risk']} | Trend: ↑
**Why Now**: {defi['catalyst']}

### ⚽ ON-PITCH: {football['league']} — {football['team']}
**Signal**: {football['stat']}
**Metric**: {football['details']}
**Why Now**: {football['signal_type'].title()} streak + favorable schedule alignment

---

⚽ **HAIKU**
{haiku_lines[0]}
{haiku_lines[1]}
{haiku_lines[2]}

---

🔗 **ACTION**
• Track vault: https://goalchain.xyz/vaults/jitosol
• Watch match: https://goalchain.xyz/fixtures/mci-wol
• Risk note: Validator concentration risk on Jito (top 3 = 42% stake); Haaland rotation risk midweek

#GoalChainAlpha #DeFiMeetsFootball"""
    return output

if __name__ == "__main__":
    print(format_alpha_signal(MOCK_DEFI, MOCK_FOOTBALL, MOCK_HAIKU))
    print("\n" + "="*60)
    print("✅ Mock Alpha Signal generated successfully")
    print("📁 Visual would be generated by alpha_signal_card.py")
    print("📊 Log would be appended to data/engagement/alpha_signal_log.json")