#!/usr/bin/env python3
"""
Test Match Preview with mock data - demonstrates the full output format.
"""

import json
from datetime import datetime

MOCK_MATCH = {
    "home": "Manchester City",
    "away": "Wolves",
    "league": "Premier League",
    "date": "08/06",
    "kickoff": "15:00",
    "stadium": "Etihad Stadium"
}

MOCK_TACTICAL = [
    "City 3-2-4-1 → 2-3-5 in possession; Wolves 5-4-1 low block, counter via Neto",
    "Haaland vs Toti Gomes: aerial dominance (4.2 aerials won/90) vs physical reset",
    "De Bruyne half-space pockets → cutback to Haaland; Wolves overload left flank"
]

MOCK_PLAYER = "Erling Haaland — FWD — xG/90 1.24 | 4 goals last 2 | Shots on target 3.1/90"

MOCK_BETTING = "Haaland Anytime Scorer @ 1.57 — xG differential + fixture ease + form streak | Kelly: 1.2% | Max: 1.5u"

MOCK_HAIKU = """City machine hums
Wolves pack sits deep and waits
One touch breaks the line"""

def format_match_preview(match, tactical, player, betting, haiku):
    today = datetime.now().strftime("%d/%m")
    haiku_lines = haiku.strip().split('\n')
    
    output = f"""🎯 **MATCH PREVIEW**: {match['home']} vs {match['away']} — {match['league']}
📅 {match['date']} | ⏰ {match['kickoff']} | 🏟️ {match['stadium']}

📊 **TACTICAL KEYS** (3 bullets max)
- {tactical[0]}
- {tactical[1]}
- {tactical[2]}

⭐ **PLAYER TO WATCH**
{player}
→ **Prop**: Haaland Anytime Scorer @ 1.57

💰 **BETTING ANGLE**
{betting}

⚽ **HAIKU**
{haiku_lines[0]}
{haiku_lines[1]}
{haiku_lines[2]}

---

🔗 **TRACK**
• GC Prediction Tracker: https://goalchain.xyz/predictions/mci-wol
• Odds Compare: https://oddsportal.com/soccer/england/premier-league/manchester-city-wolves/
• Live Thread: #🔮┃match-predictions

#GoalChainPreview #PremierLeague #MCIWOL"""
    return output

if __name__ == "__main__":
    print(format_match_preview(MOCK_MATCH, MOCK_TACTICAL, MOCK_PLAYER, MOCK_BETTING, MOCK_HAIKU))
    print("\n" + "="*60)
    print("✅ Mock Match Preview generated successfully")
    print("📁 Visual would be generated by match_preview_card.py")
    print("📊 Log would be appended to data/engagement/match_preview_log.json")