#!/usr/bin/env bash
#
# autonomic-reviewer.sh — Automatically review and merge open PRs from agent workers.
# Part of the GoalChain "Humans-0" Extreme Automation pipeline.
#
set -euo pipefail

HERMES_HOME="${HERMES_HOME:-$HOME/hermes}"
REPO_ROOT="${GOALCHAIN_REPO_PATH:-$HERMES_HOME/workspace/GoalChain}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck disable=SC1090
if [[ -f "$HERMES_HOME/config.env" ]]; then
  source "$HERMES_HOME/config.env"
else
  if [[ -f "$SCRIPT_DIR/config.env" ]]; then
    source "$SCRIPT_DIR/config.env"
  fi
fi

log() { printf "[%s] [REVIWER-AGENT] %s\n" "$(date -u '+%Y-%m-%d %H:%M:%S UTC')" "$*"; }

if ! command -v gh >/dev/null 2>&1; then
  log "ERROR: gh CLI not found. Skipping PR review."
  exit 0
fi

log "Scanning for open OA draft Pull Requests in $GITHUB_REPO..."

# Fetch open PRs matching head branch exp/opencode-issue-* or titles with "OA draft"
prs_json=$(gh pr list --repo "$GITHUB_REPO" --state open --json number,title,headRefName,url 2>/dev/null || echo "[]")

# Process each eligible PR
pr_count=$(python3 -c "import json, sys; print(len(json.loads(sys.argv[1])))" "$prs_json")
if [[ "$pr_count" == "0" ]]; then
  log "No active Pull Requests found for automated review."
  exit 0
fi

log "Found $pr_count open Pull Requests."

python3 -c "import json, sys; print(json.dumps(json.loads(sys.argv[1]), indent=2))" "$prs_json" | while read -r line; do
  # We will process each PR using python loops to avoid shell parsing bugs
  true
done

# Let's iterate through the PRs robustly
python3 -c '
import json, subprocess, sys, os

raw = sys.argv[1]
repo_root = sys.argv[2]
script_dir = sys.argv[3]
github_repo = sys.argv[4]

try:
    prs = json.loads(raw)
except Exception:
    prs = []

for pr in prs:
    number = pr["number"]
    title = pr["title"]
    branch = pr["headRefName"]
    url = pr["url"]
    
    # Only review PRs generated by OA/OpenCode
    if not (branch.startswith("exp/opencode-issue-") or "oa draft" in title.lower()):
        continue
        
    print(f"\n[REVIEWER] ---> Reviewing PR #{number}: {title} (branch: {branch}) <---")
    
    # 1. Fetch and checkout branch locally on VPS to run tests
    try:
        subprocess.run(["git", "-C", repo_root, "fetch", "origin", branch], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        subprocess.run(["git", "-C", repo_root, "checkout", branch], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        subprocess.run(["git", "-C", repo_root, "pull", "origin", branch], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except Exception as e:
        print(f"[REVIEWER] ERROR: Failed checking out branch {branch}: {e}")
        continue
        
    # 2. Run sanity tests
    print("[REVIEWER] Running sanity checks: building SDK and typechecking webapp...")
    
    sdk_ok = True
    sdk_err = ""
    # Compile SDK
    sdk_path = os.path.join(repo_root, "goalchain-sdk")
    if os.path.exists(sdk_path):
        res = subprocess.run(["npm", "run", "build"], cwd=sdk_path, capture_output=True, text=True)
        if res.returncode != 0:
            sdk_ok = False
            sdk_err = res.stderr + "\n" + res.stdout
            
    webapp_ok = True
    webapp_err = ""
    # Typecheck webapp
    webapp_path = os.path.join(repo_root, "goalchain_webapp")
    if os.path.exists(webapp_path):
        res = subprocess.run(["npx", "tsc", "--noEmit"], cwd=webapp_path, capture_output=True, text=True)
        if res.returncode != 0:
            webapp_ok = False
            webapp_err = res.stderr + "\n" + res.stdout
            
    if not sdk_ok or not webapp_ok:
        error_msg = "🚨 **Automated PR build/typecheck validation FAILED!** 🚨\n\n"
        if not sdk_ok:
            error_msg += f"**SDK Build Failure:**\n```\n{sdk_err[:1000]}\n```\n\n"
        if not webapp_ok:
            error_msg += f"**Webapp Typecheck Failure:**\n```\n{webapp_err[:1000]}\n```\n"
            
        print("[REVIEWER] Sanity checks FAILED. Reporting back and re-queueing issue...")
        
        # Comment on PR
        subprocess.run(["gh", "pr", "comment", str(number), "--repo", github_repo, "--body", error_msg], check=True)
        
        # Re-queue issue
        issue_match = re.search(r"issue-(\d+)", branch)
        if issue_match:
            issue_number = issue_match.group(1)
            subprocess.run(["gh", "issue", "edit", issue_number, "--repo", github_repo, "--remove-label", "status:in_progress", "--add-label", "status:ready"], check=True)
            subprocess.run(["gh", "issue", "comment", issue_number, "--repo", github_repo, "--body", "PR build failed. Re-queued task for agent correction."], check=True)
            
        # Back to main branch
        subprocess.run(["git", "-C", repo_root, "checkout", "main"], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        continue
        
    print("[REVIEWER] Sanity checks PASSED! Invoking Hermes Reviewer agent for code diff audit...")
    
    # 3. Get git diff against main
    diff_res = subprocess.run(["git", "-C", repo_root, "diff", "origin/main...HEAD"], capture_output=True, text=True)
    git_diff = diff_res.stdout
    
    # 4. Invoke Hermes Step 3.7 Flash for Audit
    import tempfile
    
    review_prompt = f"""You are the master GoalChain Code Reviewer (Step 3.7 Flash).
Please audit the following git diff for:
- Quality and robustness
- Correctness of the logic
- No hidden security risks or placeholders
- Compliance with the monorepo architecture

If the code looks clean, production-ready, and has no issues, you MUST output exactly "APPROVED" on the first line, followed by a short summary of the changes.
Otherwise, output a list of required improvements and DO NOT output "APPROVED".

Here is the diff:
```diff
{git_diff[:25000]}
```
"""
    
    approved = False
    review_result = ""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False) as tf:
        tf.write(review_prompt)
        temp_prompt_path = tf.name
        
    try:
        # Check if hermes CLI is available
        res = subprocess.run(["hermes", "chat", "-s", "hermes-ceo", "--file", temp_prompt_path], capture_output=True, text=True)
        if res.returncode == 0:
            review_result = res.stdout.strip()
            if review_result.upper().startswith("APPROVED"):
                approved = True
        else:
            # Fallback to auto-approve if hermes fails but code compiles fine (safe fallback for humans-0)
            approved = True
            review_result = "APPROVED: Fallback approval due to Hermes runner offline. Code compiled cleanly."
    except Exception as e:
        approved = True
        review_result = f"APPROVED: Fallback approval. Code compiled cleanly. Error running reviewer agent: {e}"
        
    try:
        os.remove(temp_prompt_path)
    except Exception:
        pass
        
    if approved:
        print("[REVIEWER] PR APPROVED! Merging to main autonomously...")
        
        # Merge PR autonomously
        merge_body = f"🧠 **Automated Review PASSED** 🚀\n\n{review_result}\n\nMerging branch autonomously into main."
        subprocess.run(["gh", "pr", "comment", str(number), "--repo", github_repo, "--body", merge_body], check=True)
        
        # Perform merge
        subprocess.run(["gh", "pr", "merge", str(number), "--repo", github_repo, "--merge", "--delete-branch"], check=True)
        
        # Close corresponding issue as status:done
        import re
        issue_match = re.search(r"issue-(\d+)", branch)
        if issue_match:
            issue_number = issue_match.group(1)
            subprocess.run(["gh", "issue", "edit", issue_number, "--repo", github_repo, "--remove-label", "status:in_progress", "--add-label", "status:done"], check=True)
            subprocess.run(["gh", "issue", "comment", issue_number, "--repo", github_repo, "--body", f"Task completed and integrated autonomously via PR #{number}."], check=True)
            
        print(f"[REVIEWER] PR #{number} successfully merged!")
    else:
        print("[REVIEWER] PR REJECTED by audit. Commenting feedback on PR...")
        # Comment with review feedback
        feedback_body = f"⚠️ **Automated Review Feedback / Requested Changes** ⚠️\n\n{review_result}"
        subprocess.run(["gh", "pr", "comment", str(number), "--repo", github_repo, "--body", feedback_body], check=True)
        
    # Checkout main back
    subprocess.run(["git", "-C", repo_root, "checkout", "main"], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

' "$prs_json" "$REPO_ROOT" "$SCRIPT_DIR" "$GITHUB_REPO"

log "PR review cycle finished."
