using System;
using System.Threading.Tasks;
using UnityEngine;
using GoalChain.Services;
using GoalChain.Autogenerated;
using Solana.Unity.Wallet;
using Solana.Unity.Rpc.Models;
using Solana.Unity.SDK;
using System.Collections.Generic;

namespace GoalChain.Managers
{
    public class FixtureBettingManager : MonoBehaviour
    {
        public GoalChainDataService dataService;
        public string currentMatchId = "ARG_POR_QTR"; // Argentina vs Portugal - Cuartos

        [Header("Live Odds & Sentiment")]
        public float teamAProbability;
        public float teamBProbability;
        public float potentialPayoutMultiplier;

        private Fixture _currentFixture;

        /// <summary>
        /// Actualiza los pools y calcula las cuotas en tiempo real.
        /// </summary>
        public async Task RefreshLiveOdds()
        {
            _currentFixture = await dataService.GetFixtureDataAsync(currentMatchId);

            if (_currentFixture == null) return;

            ulong totalPool = _currentFixture.PoolA + _currentFixture.PoolB + _currentFixture.PoolDraw;
            
            if (totalPool > 0)
            {
                teamAProbability = (_currentFixture.PoolA / (float)totalPool) * 100f;
                teamBProbability = (_currentFixture.PoolB / (float)totalPool) * 100f;
                
                Debug.Log($"[Live Betting] Pool A: {_currentFixture.PoolA} GCH ({teamAProbability:F1}%)");
                Debug.Log($"[Live Betting] Pool B: {_currentFixture.PoolB} GCH ({teamBProbability:F1}%)");
            }
        }

        /// <summary>
        /// Realiza la apuesta en la blockchain.
        /// </summary>
        public async Task PlaceBetAsync(MatchResult prediction, ulong amount, string userTokenAccount)
        {
            if (Web3.Instance.Wallet == null) return;

            PublicKey user = Web3.Instance.Wallet.Account.PublicKey;
            PublicKey fixturePda = GoalChainHelper.FindFixturePda(currentMatchId);
            PublicKey userBetPda = GoalChainHelper.FindUserBetPda(user, fixturePda);
            PublicKey fixtureVault = GoalChainHelper.FindFixtureVaultPda(fixturePda);

            var instruction = GoalChainInstructions.PlaceBet(
                user,
                fixturePda,
                userBetPda,
                new PublicKey(userTokenAccount),
                fixtureVault,
                new PublicKey(dataService.tokenMint), // Supongamos que está en dataService
                prediction,
                amount
            );

            Debug.Log($"[Betting] Enviando apuesta de {amount} GCH por {prediction}...");
            
            var tx = new Transaction { Instructions = new List<TransactionInstruction> { instruction } };
            // await Web3.Instance.Wallet.SignAndSendTransaction(tx);
        }
    }
}
