using System;
using System.Threading.Tasks;
using UnityEngine;
using Solana.Unity.Rpc;
using Solana.Unity.Rpc.Models;
using Solana.Unity.SDK;
using Solana.Unity.Wallet;
using GoalChain.Autogenerated;
using System.Collections.Generic;

namespace GoalChain.Services
{
    /// <summary>
    /// Servicio para leer datos directamente de la blockchain de Solana.
    /// </summary>
    public class GoalChainDataService : MonoBehaviour
    {
        public static GoalChainDataService Instance { get; private set; }

        private IRpcClient _rpcClient;
        public string tokenMint = "TU_TOKEN_MINT_AQUÍ";

        void Awake()
        {
            if (Instance == null) Instance = this;
            else Destroy(gameObject);
        }

        void Start()
        {
            // Conectamos al cliente RPC (Devnet por defecto en este punto del proyecto)
            _rpcClient = ClientFactory.GetClient(Cluster.DevNet);
        }

        /// <summary>
        /// Obtiene los datos de un jugador dinámico desde la blockchain.
        /// </summary>
        public async Task<ParodyPlayer> GetPlayerDataAsync(string playerId)
        {
            // 1. Calculamos la dirección (PDA) del jugador
            PublicKey playerPda = GoalChainHelper.FindParodyPlayerPda(playerId);
            Debug.Log($"[DataService] Buscando datos en: {playerPda}");

            // 2. Pedimos la cuenta a la red
            var accountInfo = await _rpcClient.GetAccountInfoAsync(playerPda);

            if (accountInfo.WasSuccessful && accountInfo.Result.Value != null)
            {
                byte[] data = Convert.FromBase64String(accountInfo.Result.Value.Data[0]);
                
                // 3. Deserializamos (Saltando los 8 bytes del discriminador de Anchor)
                return DeserializeParodyPlayer(data);
            }

            Debug.LogWarning($"[DataService] No se encontró el jugador {playerId} en la blockchain.");
            return null;
        }

        /// <summary>
        /// Traductor manual de bytes (Borsh) a nuestra clase C#.
        /// </summary>
        private ParodyPlayer DeserializeParodyPlayer(byte[] data)
        {
            // Anchor usa 8 bytes de 'Discriminator' al inicio, los saltamos.
            int offset = 8;

            try {
                var player = new ParodyPlayer();

                // 1. Leer Name (String en Borsh: 4 bytes de largo + contenido)
                int nameLen = BitConverter.ToInt32(data, offset); offset += 4;
                player.Name = System.Text.Encoding.UTF8.GetString(data, offset, nameLen);
                offset += nameLen;

                // 2. Leer PlayerId (String)
                int idLen = BitConverter.ToInt32(data, offset); offset += 4;
                player.PlayerId = System.Text.Encoding.UTF8.GetString(data, offset, idLen);
                offset += idLen;

                // 3. Leer Stats (u8)
                player.RealWorldGoals = data[offset++];
                player.RealWorldAssists = data[offset++];
                player.MatchesPlayed = data[offset++];
                player.Speed = data[offset++];
                player.ShotPower = data[offset++];

                return player;
            }
            catch (Exception e)
            {
                Debug.LogError($"[DataService] Error al deserializar: {e.Message}");
                return null;
            }
        }
        public async Task<Fixture> GetFixtureDataAsync(string matchId)
        {
            PublicKey fixturePda = GoalChainHelper.FindFixturePda(matchId);
            var accountInfo = await _rpcClient.GetAccountInfoAsync(fixturePda);

            if (accountInfo.WasSuccessful && accountInfo.Result.Value != null)
            {
                byte[] data = Convert.FromBase64String(accountInfo.Result.Value.Data[0]);
                return DeserializeFixture(data);
            }
            return null;
        }

        private Fixture DeserializeFixture(byte[] data)
        {
            int offset = 8; // Skip discriminator
            var fixture = new Fixture();

            // MatchId
            int idLen = BitConverter.ToInt32(data, offset); offset += 4;
            fixture.MatchId = System.Text.Encoding.UTF8.GetString(data, offset, idLen);
            offset += idLen;

            // TeamA
            int aLen = BitConverter.ToInt32(data, offset); offset += 4;
            fixture.TeamA = System.Text.Encoding.UTF8.GetString(data, offset, aLen);
            offset += aLen;

            // TeamB
            int bLen = BitConverter.ToInt32(data, offset); offset += 4;
            fixture.TeamB = System.Text.Encoding.UTF8.GetString(data, offset, bLen);
            offset += bLen;

            fixture.PoolA = BitConverter.ToUInt64(data, offset); offset += 8;
            fixture.PoolB = BitConverter.ToUInt64(data, offset); offset += 8;
            fixture.PoolDraw = BitConverter.ToUInt64(data, offset); offset += 8;
            
            fixture.Status = (MatchStatus)data[offset++];
            
            // Winner (Option<MatchResult>)
            if (data[offset++] == 1) {
                fixture.Winner = (MatchResult)data[offset++];
            } else {
                offset++; // Skip inner byte
                fixture.Winner = null;
            }

            fixture.StartTimestamp = BitConverter.ToInt64(data, offset);
            return fixture;
        }
    }
}
