using System.Collections;
using UnityEngine;
using GoalChain.Services;
using GoalChain.UI;
using GoalChain.Autogenerated;

namespace GoalChain.Managers
{
    /// <summary>
    /// El manager principal que coordina el flujo del juego con la Blockchain.
    /// </summary>
    public class GoalChainManager : MonoBehaviour
    {
        public static GoalChainManager Instance { get; private set; }

        [Header("Referencias de Escena")]
        public PenaltyUI penaltyUI;
        public GoalChainDataService dataService;

        [Header("Jugadores Actuales")]
        public string localPlayerId = "lionel_bitcoin";
        public string opponentPlayerId = "cristiano_ethereum";

        private ParodyPlayer _localPlayerData;
        private ParodyPlayer _opponentPlayerData;

        void Awake()
        {
            Instance = this;
        }

        async void Start()
        {
            Debug.Log("🚀 GoalChain: Iniciando sincronización con Solana...");
            
            // 1. Cargar datos reales de la red
            _localPlayerData = await dataService.GetPlayerDataAsync(localPlayerId);
            _opponentPlayerData = await dataService.GetPlayerDataAsync(opponentPlayerId);

            if (_localPlayerData != null && _opponentPlayerData != null)
            {
                Debug.Log($"✅ Datos cargados: {_localPlayerData.Name} tiene {_localPlayerData.RealWorldGoals} goles reales.");
                
                // 2. Inyectar datos en la UI
                UpdateGameUI();
            }
            else
            {
                Debug.LogError("❌ Fallo en la carga de datos de Solana. Revisa la conexión o el ID del jugador.");
            }
        }

        private void UpdateGameUI()
        {
            // Mapeamos los datos de la Autogenerated.ParodyPlayer a lo que la UI espera
            // (En un paso final unificaremos namespaces para limpieza)
            penaltyUI.localPlayerNameText.text = $"{_localPlayerData.Name} ({_localPlayerData.RealWorldGoals} G)";
            penaltyUI.opponentPlayerNameText.text = $"{_opponentPlayerData.Name} ({_opponentPlayerData.RealWorldGoals} G)";
            
            penaltyUI.SetStatusMessage("¡Conexión On-Chain Establecida!");
        }

        public byte GetLocalShotPower()
        {
            return _localPlayerData != null ? _localPlayerData.ShotPower : (byte)50;
        }
    }
}
