using System.Numerics;
using Solana.Unity.Programs.Utilities;
using Solana.Unity.Rpc.Models;
using GoalChain.Autogenerated;
using UnityEngine;

namespace GoalChain.Models
{
    /// <summary>
    /// Modelo de datos que mapea la cuenta 'ParodyPlayer' de nuestro Smart Contract en Solana.
    /// Utiliza los tipos de Solana.Unity SDK para deserializar la data On-Chain.
    /// </summary>
    public class ParodyPlayer
    {
        public string Name { get; set; }
        public string PlayerId { get; set; }
        public byte RealWorldGoals { get; set; }
        public byte RealWorldAssists { get; set; }
        public byte MatchesPlayed { get; set; }
        public byte Speed { get; set; }
        public byte ShotPower { get; set; }

        /// <summary>
        /// Deserializa el layout de Anchor (Borsh) a la estructura de C#
        /// </summary>
        public static ParodyPlayer Deserialize(byte[] data)
        {
            // Omitimos la deserialización real temporalmente para probar la UI
            // sin depender de la carga del SDK de Solana en Unity.
            var player = new ParodyPlayer();
            player.Name = "Lionel Bitcoin";
            player.ShotPower = 95;
            return player;
        }

        public void PrintStats()
        {
            Debug.Log($"[ParodyPlayer] {Name} (ID: {PlayerId}) - Speed: {Speed}, Shot Power: {ShotPower}");
        }
    }
}
