using GoalChain.Autogenerated;
using GoalChain.Managers;
using GoalChain.UI;

namespace GoalChain.GamePlay
{
    public class PenaltyGameMode : MonoBehaviour
    {
        [Header("Managers Reference")]
        public WagerManager wagerManager;
        public PenaltyUI uiManager;

        [Header("Match Settings")]
        public int totalRounds = 5;
        
        [Header("Players Data (NFTs)")]
        private ParodyPlayer localPlayerNFT; 
        private ParodyPlayer opponentPlayerNFT;

        private string currentWagerId;

        // Estado del partido
        private int currentRound = 1;
        private int localScore = 0;
        private int opponentScore = 0;
        private bool isLocalTurnToShoot = true;

        public void StartPenaltyMatch(ParodyPlayer local, ParodyPlayer opponent, string wagerId)
        {
            localPlayerNFT = local;
            opponentPlayerNFT = opponent;
            currentWagerId = wagerId;
            
            currentRound = 1;
            localScore = 0;
            opponentScore = 0;
            isLocalTurnToShoot = true;

            Debug.Log($"¡El partido comienza! {local.Name} vs {opponent.Name} | Wager: {wagerId}");
            if (uiManager != null) uiManager.InitializeMatchUI(local, opponent, 50);

            NextTurn();
        }

        private void NextTurn()
        {
            if (currentRound > totalRounds)
            {
                CheckWinnerAndResolve();
                return;
            }

            if (uiManager != null) uiManager.UpdateScore(localScore, opponentScore, currentRound);

            if (isLocalTurnToShoot)
            {
                string msg = $"[Ronda {currentRound}] ¡Tu turno!";
                if (uiManager != null) uiManager.SetStatusMessage(msg);
                SimulateShootAction(localPlayerNFT, true);
            }
            else
            {
                string msg = $"[Ronda {currentRound}] ¡Turno Oponente!";
                if (uiManager != null) uiManager.SetStatusMessage(msg);
                SimulateShootAction(opponentPlayerNFT, false);
            }
        }

        public void SimulateShootAction(ParodyPlayer shooter, bool isLocal)
        {
            float baseChance = 0.5f;
            float shotBonus = (shooter.ShotPower * 0.02f); 
            float finalGoalChance = baseChance + shotBonus;

            bool isGoal = Random.Range(0f, 1f) <= finalGoalChance;

            if (isGoal)
            {
                if (uiManager != null) uiManager.ShowGoalAnimation();
                if (isLocal) localScore++; else opponentScore++;
            }
            else
            {
                if (uiManager != null) uiManager.ShowMissAnimation();
            }

            if (!isLocalTurnToShoot) currentRound++;
            isLocalTurnToShoot = !isLocalTurnToShoot;
            
            StartCoroutine(DelayNextTurn());
        }

        private IEnumerator DelayNextTurn()
        {
            yield return new WaitForSeconds(2f);
            NextTurn();
        }

        private void CheckWinnerAndResolve()
        {
            if (localScore > opponentScore)
            {
                if (uiManager != null) uiManager.SetStatusMessage("<color=yellow>¡GANASTE!</color>");
                if (wagerManager != null) _ = wagerManager.ResolveWagerAsync(currentWagerId, true);
            }
            else if (opponentScore > localScore)
            {
                if (uiManager != null) uiManager.SetStatusMessage("<color=red>PERDISTE</color>");
                if (wagerManager != null) _ = wagerManager.ResolveWagerAsync(currentWagerId, false);
            }
            else
            {
                totalRounds++;
                NextTurn();
            }
        }
    }
}
    }
}
