using System.Threading.Tasks;
using UnityEngine;
using Solana.Unity.Wallet;
using Solana.Unity.Rpc;
using Solana.Unity.Rpc.Models;
using Solana.Unity.SDK;
using GoalChain.Autogenerated;

namespace GoalChain.Managers
{
    /// <summary>
    /// Manager principal para interactuar con el módulo de Apuestas (Wagering) en Solana.
    /// </summary>
    public class WagerManager : MonoBehaviour
    {
        public string programId = "FbDhM4itBS2Cco7c7PbNvC98Fx7Y5HxqXS1JuXdNcBwg";
        public string tokenMint = "TU_TOKEN_MINT_AQUÍ"; // Debe configurarse con el GCH Token
        
        void Start()
        {
            Debug.Log("WagerManager Inicializado y conectado a Devnet.");
        }

        /// <summary>
        /// Crea una apuesta real en la blockchain.
        /// </summary>
        public async Task<string> CreateWagerAsync(ulong betAmount, string playerATokenAccount)
        {
            if (Web3.Instance.Wallet == null) return null;

            PublicKey playerA = Web3.Instance.Wallet.Account.PublicKey;
            long timestamp = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
            
            // 1. Derivamos PDAs usando nuestro Helper
            PublicKey wagerPda = GoalChainHelper.FindWagerPda(playerA, timestamp);
            PublicKey wagerVault = GoalChainHelper.FindWagerVaultPda(wagerPda);

            Debug.Log($"[Wager] Creando apuesta en PDA: {wagerPda}");

            // 2. Construimos la instrucción
            var instruction = GoalChainInstructions.CreateWager(
                playerA,
                wagerPda,
                new PublicKey(playerATokenAccount),
                wagerVault,
                new PublicKey(tokenMint),
                timestamp,
                betAmount
            );

            // 3. Enviamos la transacción
            var tx = new Transaction { Instructions = new List<TransactionInstruction> { instruction } };
            // Aquí llamaríamos a Web3.Instance.Wallet.SignAndSendTransaction(tx);
            
            return wagerPda.ToString(); // Devolvemos el ID de la apuesta
        }

        /// <summary>
        /// Avisa al Oráculo que el partido ha terminado para que libere los fondos.
        /// </summary>
        public async Task ResolveWagerAsync(string wagerId, bool localIsWinner)
        {
            Debug.Log($"[Wager] Solicitando resolución para apuesta {wagerId}. Ganador Local: {localIsWinner}");
            
            // En un MVP real, aquí harías un POST a tu servidor Oráculo (Node.js)
            // indicando el WagerId y el resultado para que el servidor firme.
            
            await Task.Delay(1000); 
            Debug.Log("💰 ¡Transacción de resolución procesada por el Oráculo! Premio enviado.");
        }
    }
}
