using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
using GoalChain.Autogenerated;
using GoalChain.Services;

namespace GoalChain.UI
{
    public class WorldCupBracketUI : MonoBehaviour
    {
        public GoalChainDataService dataService;
        
        // IDs de los partidos que queremos monitorizar en el cuadro
        private string[] _quarterFinalIds = { "ARG_POR_QTR", "BRA_ENG_QTR", "FRA_GER_QTR", "SPA_ITA_QTR" };
        private string _propBetId = "ARG_CHAMP_YES_NO";

        [Header("UI Elements (Mockup References)")]
        public List<GameObject> matchSlots; // Slots visuales en el árbol

        /// <summary>
        /// Carga todos los pools del mundial y actualiza el cuadro visual.
        /// </summary>
        public async void RefreshTournamentData()
        {
            Debug.Log("📡 Sincronizando Cuadro del Mundial desde Solana...");

            foreach (var matchId in _quarterFinalIds)
            {
                var fixture = await dataService.GetFixtureDataAsync(matchId);
                if (fixture != null)
                {
                    UpdateMatchUI(fixture);
                }
            }

            // Cargar el mercado Polymarket de Argentina
            var propBet = await dataService.GetFixtureDataAsync(_propBetId);
            if (propBet != null)
            {
                Debug.Log($"[Polymarket] Sentimiento ARG Campeón: SÍ {CalculateSentiment(propBet)}%");
            }
        }

        private void UpdateMatchUI(Fixture fixture)
        {
            // Aquí iría la lógica para asignar nombres y banderas a los slots de Unity
            Debug.Log($"[Bracket] {fixture.TeamA} vs {fixture.TeamB} | Pool Total: {fixture.PoolA + fixture.PoolB} GCH");
        }

        private float CalculateSentiment(Fixture f)
        {
            ulong total = f.PoolA + f.PoolB;
            if (total == 0) return 50f;
            return (f.PoolA / (float)total) * 100f;
        }
    }
}
