import discord
import os
from requests_oauthlib import OAuth1

DISCORD_TOKEN = "MTUwNDIwNDc3ODEwMjcyMjc1MA.G4cT6l.a3G33fhdtYgXK3CputA8atB3qWYDCGHRCz67Qw"
ANNOUNCEMENTS_CHANNEL_ID = 1503668120521408513

intents = discord.Intents.default()
intents.guilds = True

client = discord.Client(intents=intents)

@client.event
async def on_ready():
    print(f"🤖 Bot conectado como: {client.user}")
    
    channel = client.get_channel(ANNOUNCEMENTS_CHANNEL_ID)
    if not channel:
        print(f"❌ Canal de anuncios con ID {ANNOUNCEMENTS_CHANNEL_ID} no encontrado.")
        await client.close()
        return
        
    print(f"🚀 Creando y enviando anuncio oficial a #{channel.name}...")
    
    # Sunset image or promo image to attach to the announcements
    image_path = "/Users/NicoPez/GoalChain/docs/assets/img/nfts/bg/bg_rare_sunset.png"
    file_name = os.path.basename(image_path)
    file = discord.File(image_path, filename=file_name)
    
    # Premium Embed
    embed = discord.Embed(
        title="📢 SYSTEM UPDATE: ROADMAP 2026 & TOKENOMICS 2.0 RELEASED! 🗺️📊",
        description=(
            "🚨 **Attention Managers!** 🚨\n\n"
            "We have just pushed a massive double-update to the GoalChain platform to align our roadmap, technical trajectory, and decentralized economy for the upcoming **FIFA World Cup 2026**! 🏆🔥\n\n"
            "Here is everything you need to know about today's launch:\n\n"
            "---"
        ),
        color=0x14F195 # Solana Green
    )
    
    embed.add_field(
        name="🗺️ 1. ROADMAP 2026-2027 UPDATED",
        value=(
            "• **Q2 2026 (✅ Completed):** Alpha launch of the browser Penalty Arcade game & bilingual Spanish/English integration.\n"
            "• **Q2/Q3 2026 (⚡ NOW ACTIVE):** Zealy Questroom launch & social ad boost campaigns.\n"
            "• **Coming Next (🔮 World Cup 2026):** **The Oracle Live** betting pools with instant Solana settlement!"
        ),
        inline=False
    )
    
    embed.add_field(
        name="📊 2. TOKENOMICS 2.0 DIRECTORY LIVE",
        value=(
            "We have officially released the full technical breakdown of the **$GCH Circular Economy** in our whitepaper:\n"
            "• **Total Supply:** 100,000,000 $GCH (Fixed Maximum).\n"
            "• **30% Play-to-Airdrop:** Distributed directly via Penalty shootout achievements.\n"
            "• **30% Ecosystem & Jackpot:** Locked in the World Cup Jackpot pool.\n"
            "• **15% Marketing & Zealy:** Backing our community building campaigns.\n"
            "• **15% Liquidity (DEX Pool):** LP keys permanently burned.\n"
            "• **10% Core Team & DAO Treasury:** Locked with a strict 6-month cliff."
        ),
        inline=False
    )
    
    embed.add_field(
        name="🛡️ 3. THE INFINITY ENGINE MEV FLYWHEEL",
        value=(
            "Learn how **JitoSOL Liquid Staking APY** and MEV tips generated by our treasury are dynamically and automatically used to **buy back $GCH from liquidity pools and burn it permanently**. Our sell pressure is eaten organically!"
        ),
        inline=False
    )
    
    embed.add_field(
        name="⚡ WHAT TO DO NOW:",
        value=(
            "1️⃣ Read the full updated mega-guide on: 🔗 [goalchain.fun/mega-guide.html](https://goalchain.fun/mega-guide.html)\n"
            "2️⃣ Complete active missions on Zealy to secure your slice of the 30% airdrop allocation: 🔗 [Zealy.io](https://zealy.io/cw/goalchain)"
        ),
        inline=False
    )
    
    embed.set_image(url=f"attachment://{file_name}")
    embed.set_footer(text="GoalChain Core Operations | The Future of Football on Solana", icon_url="https://goalchain.fun/assets/img/logo_3d_clean.png")
    
    try:
        await channel.send(embed=embed, file=file)
        print("✅ ANUNCIO OFICIAL ENVIADO CON ÉXITO A DISCORD!")
    except Exception as e:
        print(f"❌ Error al enviar el anuncio: {str(e)}")
        
    await client.close()

if __name__ == "__main__":
    client.run(DISCORD_TOKEN)
