from __future__ import annotations

from goalchain_multiagent.state import GraphState


def dev_node(state: GraphState) -> GraphState:
    objective = (state.get("objective") or "").strip()
    trace = list(state.get("route_trace") or [])
    trace.append("dev")

    body = f"""## Objective
{objective}

## Context
Generated by GoalChain LangGraph Dev agent (Fase 0). Do not merge without Antigravity review.

## Allowed files
TBD — scope in intake brief.

## Out of scope
On-chain mainnet, treasury, mint gates, `ECONOMIC_CANONICAL_CONFIG.json` value changes.

## Acceptance criteria
- [ ] Tests listed in issue body pass
- [ ] Draft PR only (`exp/opencode-issue-*`)

## Owner
agent:opencode (FCC)

## Test commands
`cd goalchain_webapp && npm run build` (if webapp touched)
"""

    artifacts = list(state.get("artifacts") or [])
    artifacts.append(
        {
            "type": "github_issue_draft",
            "title": f"[LangGraph] {objective[:72]}",
            "body": body,
            "meta": {"suggested_label": "agent:opencode"},
        }
    )

    return {
        "route_trace": trace,
        "artifacts": artifacts,
        "messages": (state.get("messages") or [])
        + [
            {
                "role": "dev",
                "content": "Prepared GitHub issue draft; execution via FCC, not direct repo write.",
            }
        ],
        "next_agent": "ceo",
    }
