using System;
using System.Text;
using Solana.Unity.Wallet;

namespace GoalChain.Autogenerated
{
    public static class GoalChainHelper
    {
        public static PublicKey FindFixturePda(string matchId)
        {
            PublicKey.TryFindProgramAddress(
                new[] { Encoding.UTF8.GetBytes("fixture"), Encoding.UTF8.GetBytes(matchId) },
                GoalChainInstructions.ProgramId,
                out PublicKey pda,
                out _
            );
            return pda;
        }

        public static PublicKey FindUserBetPda(PublicKey user, PublicKey fixturePda)
        {
            PublicKey.TryFindProgramAddress(
                new[] { 
                    Encoding.UTF8.GetBytes("bet"), 
                    user.KeyBytes, 
                    fixturePda.KeyBytes 
                },
                GoalChainInstructions.ProgramId,
                out PublicKey pda,
                out _
            );
            return pda;
        }

        public static PublicKey FindFixtureVaultPda(PublicKey fixturePda)
        {
            PublicKey.TryFindProgramAddress(
                new[] { Encoding.UTF8.GetBytes("fixture_vault"), fixturePda.KeyBytes },
                GoalChainInstructions.ProgramId,
                out PublicKey pda,
                out _
            );
            return pda;
        }
        
        // ... Otros helpers ...
    }
}
