using System;
using System.Collections.Generic;
using Solana.Unity.Rpc.Models;
using Solana.Unity.Wallet;
using Solana.Unity.Programs;
using Solana.Unity.Programs.Utilities;

namespace GoalChain.Autogenerated
{
    public static class GoalChainInstructions
    {
        public static readonly PublicKey ProgramId = new PublicKey("FbDhM4itBS2Cco7c7PbNvC98Fx7Y5HxqXS1JuXdNcBwg");

        // Discriminadores DEFINITIVOS (Extraídos del IDL v2.0)
        public static readonly byte[] InitializeFixtureDisc = { 26, 99, 178, 9, 192, 14, 167, 207 };
        public static readonly byte[] PlaceBetDisc = { 222, 62, 67, 220, 63, 166, 126, 33 };
        public static readonly byte[] CreateWagerDisc = { 210, 82, 178, 75, 253, 34, 84, 120 };
        public static readonly byte[] ResolveWagerDisc = { 31, 179, 1, 228, 83, 224, 1, 123 };

        public static TransactionInstruction PlaceBet(
            PublicKey user,
            PublicKey fixturePda,
            PublicKey userBetPda,
            PublicKey userTokenAccount,
            PublicKey fixtureVault,
            PublicKey tokenMint,
            MatchResult prediction,
            ulong amount
        )
        {
            List<AccountMeta> keys = new List<AccountMeta>
            {
                AccountMeta.Writable(user, true),
                AccountMeta.Writable(fixturePda, false),
                AccountMeta.Writable(userBetPda, false),
                AccountMeta.Writable(userTokenAccount, false),
                AccountMeta.Writable(fixtureVault, false),
                AccountMeta.ReadOnly(tokenMint, false),
                AccountMeta.ReadOnly(TokenProgram.ProgramIdKey, false),
                AccountMeta.ReadOnly(SystemProgram.ProgramIdKey, false),
            };

            byte[] data = new byte[8 + 1 + 8];
            Array.Copy(PlaceBetDisc, 0, data, 0, 8);
            data[8] = (byte)prediction;
            Array.Copy(BitConverter.GetBytes(amount), 0, data, 9, 8);

            return new TransactionInstruction
            {
                ProgramId = ProgramId.KeyBytes,
                Keys = keys,
                Data = data
            };
        }
    }
}
