using System;
using System.Collections.Generic;
using Solana.Unity.Rpc.Models;
using Solana.Unity.Wallet;

namespace GoalChain.Autogenerated
{
    public enum MatchStatus : byte
    {
        Upcoming = 0,
        Live = 1,
        Completed = 2,
        Cancelled = 3
    }

    public enum MatchResult : byte
    {
        TeamA = 0,
        TeamB = 1,
        Draw = 2
    }

    public enum WagerState : byte
    {
        Created = 0,
        Accepted = 1,
        Resolved = 2
    }

    public class Fixture
    {
        public string MatchId;
        public string TeamA;
        public string TeamB;
        public ulong PoolA;
        public ulong PoolB;
        public ulong PoolDraw;
        public MatchStatus Status;
        public MatchResult? Winner; // Optional
        public long StartTimestamp;
    }

    public class UserBet
    {
        public PublicKey Owner;
        public PublicKey Fixture;
        public ulong Amount;
        public MatchResult Prediction;
        public long BetTimestamp;
        public bool Claimed;
    }

    public class ParodyPlayer
    {
        public string Name;
        public string PlayerId;
        public byte RealWorldGoals;
        public byte RealWorldAssists;
        public byte MatchesPlayed;
        public byte Speed;
        public byte ShotPower;
    }

    public class Wager
    {
        public PublicKey PlayerA;
        public PublicKey PlayerB;
        public ulong Amount;
        public long Timestamp;
        public byte Bump;
        public WagerState State;
    }
}
