name: Test CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello without checkout
        run: |
          echo "Hello World"
          pwd
          ls -la
